#!/usr/bin/python3

import socket
import sys
from _thread import *
import select 
import re 

if len(sys.argv)!=3:
    print("Correct input format./chatclient ip:port nickname")
    sys.exit()

server = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)


addr = (sys.argv[1])
a=addr.split(':')
ip_addr=str(a[0])
port=int(a[1])
nick=str(sys.argv[2])


server.connect((ip_addr, port))

initial_msg=server.recv(2048).decode('utf-8')

print(initial_msg)

nick = 'NICK ' + nick


server.sendall(nick.encode('utf-8'))

response=server.recv(2048).decode('utf-8')
print(response)
if response == "OK":
    pass
elif response == "ERROR: Malformed nickname":
    print('Do not enter nickname conatining special characters, limited only to 12 chars')
    print('Disconnecting, please try again with valid nickname')
    sys.exit()
    
    



while True:
    socket_list=[sys.stdin, server]  #list of input streams
    

    read_sockets,write_sockets,error_sockets=select.select(socket_list,[],[])
    
    for sockets in read_sockets:
        if sockets == server:
            message = sockets.recv(2048).decode('utf-8')
            print(message)
        else:
            message=sys.stdin.readline()
            message = 'MSG '+ message
            if message == '\n':
                continue
            else:
                server.sendall(message.encode('utf-8'))
                
server.close()
